#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jline
Version  : 2.14.6
Release  : 1
URL      : https://github.com/jline/jline2/archive/jline-2.14.6.tar.gz
Source0  : https://github.com/jline/jline2/archive/jline-2.14.6.tar.gz
Source1  : https://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.jar
Source2  : https://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.pom
Source3  : https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar
Source4  : https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jline-data = %{version}-%{release}

%description
<!--
This software is distributable under the BSD license. See the terms of the
BSD license in the documentation provided with this software.

%package data
Summary: data components for the mvn-jline package.
Group: Data

%description data
data components for the mvn-jline package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jline/jline/0.9.94
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jline/jline/0.9.94
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jline/jline/0.9.94/jline-0.9.94.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jline/jline/2.14.6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jline/jline/2.14.6
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/jline/jline/2.14.6/jline-2.14.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar
/usr/share/java/.m2/repository/jline/jline/0.9.94/jline-0.9.94.pom
/usr/share/java/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar
/usr/share/java/.m2/repository/jline/jline/2.14.6/jline-2.14.6.pom
